apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-static-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-static
  template:
    metadata:
      labels:
        app: devops-static
    spec:
      containers:
      - name: nginx
        image: joelk365/devops-static-app:latest
        ports:
        - containerPort: 80
